spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomprod
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/
  
server:
  port: 9005
